### PR TITLE
Add new `collapseLogOnStart` option

### PR DESCRIPTION
**Pull request by robinnorth**
Permits collapsing of log messages by default, if enabled

### CODE REVIEW

**Comment by mminer** [comment]
Hey @robinnorth, thanks for the pull request, and for adding the `#if UNITY_EDITOR` I should have had in there to start with.

**Comment by robinnorth** [comment]
You're very welcome, thanks for providing such an invaluable tool!

**Comment by robinnorth** [comment]
@mminer is there any chance you can tag a release with this PR in, please? It would be very helpful for something I'm working on.

**Comment by mminer** [comment]
Yessir — I tagged the new version [1.3.0](https://github.com/mminer/consolation/releases/tag/1.3.0). Sorry for the delay.

**Comment by robinnorth** [comment]
Thank you very much @mminer, it's most appreciated!

**Pull request merged**
